version: 0.1.{build}
environment:
  matrix:
    - COMPILER: msys2
      PLATFORM: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      BIT: 64
build_script:
  - SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%"
  - bash -lc "pacman -S --needed --noconfirm pacman-mirrors"
  - bash -lc "pacman -S --needed --noconfirm git"
  - bash -lc "pacman -Syu --noconfirm"
  - bash -lc "pacman -S --needed --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-make mingw-w64-x86_64-openblas"
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - mkdir build
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER/build; cmake .. -G \"MSYS Makefiles\" -DPYTHON_EXECUTABLE=C:/Python36-x64/python.exe"
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER/build; make"
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\Python36-x64\python.exe -c "import pitensor; i=pitensor.Index('I', 3); print(i)"
  - C:\Python36-x64\python.exe -c "import sys; print(sys.path)"