language: generic
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - python3 setup.py build_ext
  - python3 setup.py bdist_wheel
  - python3 setup.py install
after_success:
  - echo "Success"
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - python3
            - python3-pip
            - python3-wheel
            - liblapack-dev
            - libopenblas-dev
      env:
        - CC=gcc-7 CXX=g++-7
    - os: osx
      before_install:
        - brew update
        - brew outdated python || brew upgrade python
        - python -m pip install --upgrade pip setuptools wheel
      env:
        - CC=clang CXX=clang++
