language: generic
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - python setup.py build_ext
  - python setup.py bdist_wheel
  - python setup.py install
after_success:
  - echo "Success"
matrix:
  include:
    - os: linux
      python: "3.3"
      env:
        - CC=gcc-7 CXX=g++-7
    - os: linux
      python: "3.4"
      env:
        - CC=gcc-7 CXX=g++-7
    - os: linux
      python: "3.5"
      env:
        - CC=gcc-7 CXX=g++-7
    - os: linux
      python: "3.6"
      env:
        - CC=gcc-7 CXX=g++-7
    - os: osx
      env:
        - CC=clang CXX=clang++
before_install:
  - .travis/before_install.sh