notifications:
  email: false
branches:
  only:
  - master
script:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- python setup.py build_ext
- python setup.py bdist_wheel
- python setup.py install
after_success:
- python tests/test_itensor.py -v
matrix:
  include:
  - os: linux
    language: python
    python: '3.5'
    addons: &1
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - liblapack-dev
        - libopenblas-dev
    before_install:
    - python -m pip install --upgrade pip setuptools wheel
    env: CC=gcc-7 CXX=g++-7
  - os: linux
    language: python
    python: '3.6'
    addons: *1
    before_install:
    - python -m pip install --upgrade pip setuptools wheel
    env: CC=gcc-7 CXX=g++-7
  - os: osx
    language: generic
    before_install:
    - brew update
    - brew outdated pyenv || brew upgrade pyenv
    - brew install pyenv-virtualenv
    - eval "$(pyenv init -)"
    - pyenv install 3.6.4
    - export PYENV_VERSION=3.6.4
    - eval "$(pyenv virtualenv-init -)"
    - pyenv virtualenv venv
    - pyenv shell venv
    - which python
    - python --version
    - python -m pip install --upgrade pip setuptools wheel
    env:
    - CC=clang CXX=clang++
deploy:
  provider: bintray
  skip_cleanup: true
  file: descriptor.json
  user: kyungminlee
  key:
    secure: u1NHx/7aXJB3ofzqRMEIHwSIee90Jzc2KD1CMj0PNcIlgcZu8Ru2itnPFzmQ6pJtHOntBsI4DNhmysf1dOmpaXEBmYesaEtXIF4YaBUJdZA1Xw8aRJKx0/x6DX9ZTWkxqkpbXrKW2TCb4G/er25lb/Ukj2s/dFgs4q5M0E6GstanUd8PIfAoCja/7KcmfpC9RjzeqWwJuMS3C2V0HRCgZNxJ//OzFES4xWTKZd6vx7tcloOKGttvtTx2qr5gfhLq8r61DF+zDOayLqsWDQXaJcrD9iQso/l9usP1FuvDX9dLUwhmt6w6/BW1AXfzV1B6rDLneOqSanH6NXqwzPXE0sTlZLgc+sUodcXa17F0GlM71aNxYi++ZwkVmGZBa70gdUJkeUV4HkTrlfeHwrMUjgGy0GOlmUzM+rekaPEJ5ZsGeH1ehsA31Vvw/6ST08REVAHUnhwTm9dRAE1WLAPe+w6m/iXA8hXhVhG9BRC7KOh1R+rF86slKDniGyBFXBhrOGtiCqZWpJHSxF4Mkr8yYYPz5x59VyWQ8DMEO5ZpUtomcFL+Bqnvm9yNlrwbUpr+PZtdUb3LvxKt2nLq/GJoD4PwR7crZmsk/iS9KG1Y1Kns73m5Kik4Pp91WshRsPJWdPcMp1gF43QgVE5bCeDd3nQygFXtt36SJ2Y0mt/eX5M=
