language: generic
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - python setup.py build_ext
  - python setup.py bdist_wheel
  - python setup.py install
after_success:
  - echo "Success"
matrix:
  include:
    - os: linux
      python: "3.3"
      addons: &linux_addon
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'liblapack-dev', 'libopenblas-dev']
      before_install:
        - python -m pip install --upgrade pip setuptools wheel
      env: CC=gcc-7 CXX=g++-7
    - os: linux
      python: "3.4"
      addons: *linux_addon
      before_install:
        - python -m pip install --upgrade pip setuptools wheel
      env: CC=gcc-7 CXX=g++-7
    - os: linux
      python: "3.5"
      addons: *linux_addon
      before_install:
        - python -m pip install --upgrade pip setuptools wheel
      env: CC=gcc-7 CXX=g++-7
    - os: linux
      python: "3.6"
      addons: *linux_addon
      before_install:
        - python -m pip install --upgrade pip setuptools wheel
      env: CC=gcc-7 CXX=g++-7
    - os: osx
      before_install:
        - brew update
        - brew outdated python || brew upgrade python
        - python -m pip install --upgrade pip setuptools wheel
      env:
        - CC=clang CXX=clang++
